# Site
name: "Programming with Wade Derby"
title: "Blog | Wade Derby - Web Developer"
description: ""
meta_description: "Jekyll template, web developement, machine learning"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: ''
google_analytics: 'UA-135010947-1'
disqus: ''
mailchimp-list: ''

# Authors
authors:
  wade:
    name: Wade Derby
    display_name: Wade Derby
    avatar: avaatar.png
    email: derbywaheed@gmail.com
    web: https://wadederby.com
    twitter: https://twitter.com/wadederby
    description: "Software Engineer at Working IT Solutions, full stack web developer and designer"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge